[package]
name = "proot-rs"
version = "0.1.0"
authors = ["vincenthage"]
build = "src/build_loader.rs"

[dependencies]
libc = "0.2.25"
nix = "0.9.0"
clap = "2.25.1"
syscall = "0.2.1"
lazy_static = "0.2.8"
byteorder = "1.1.0"

[build-dependencies]
gcc = { git = "https://github.com/vincenthage/gcc-rs", branch = "master" }